### PR TITLE
feat: add password and timeout configuration for connecting to redis

### PR DESCRIPTION
**Pull request by seriouszyx**
Fix: https://github.com/jcasbin/redis-watcher/issues/11

### CODE REVIEW

**Comment by hsluoyz** [comment]
@seriouszyx plz fix:

image

**Comment by hsluoyz** [comment]
@seriouszyx can you also add this to the README as a new example? https://github.com/jcasbin/redis-watcher#simple-example

**Comment by seriouszyx** [comment]
@hsluoyz done

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
