### PR TITLE
add redis-watcher for Jcasbin

### PR DESCRIPTION
**Pull request by tangyang9464**
Fix: https://github.com/jcasbin/redis-watcher/issues/1

### CODE REVIEW

**Comment by hsluoyz** [comment]
@fangzhengjin @shy1st plz review.

**Comment by fangzhengjin** [comment]
1. Change the package name to org.casbin
2. Set the version of the compiled bytecode file to 8
3. Adjust Main.java as a test case and place it in test




---Original---
From: "Yang ***@***.***&gt;
Date: Sat, Jun 5, 2021 21:18 PM
To: ***@***.***&gt;;
Cc: "ZhengJin ***@***.***&gt;;"Review ***@***.***&gt;;
Subject: Re: [jcasbin/redis-watcher] add redis-watcher for Jcasbin (#2)




 
@hsluoyz requested your review on: #2 add redis-watcher for Jcasbin.

**Comment by tangyang9464** [comment]
@fangzhengjin It has been modified

**Comment by shy1st** [comment]
@tangyang9464 Please add the ci.

**Comment by hsluoyz** [comment]
@tangyang9464 plz always squash/merge your commits into a single commit

**Comment by fangzhengjin** [comment]
@tangyang9464 The test cases should be placed in the src/test/java directory, because they should not be compiled into a jar.

**Comment by tangyang9464** [comment]
@shy1st @fangzhengjin completed

**Comment by fangzhengjin** [comment]
@tangyang9464 plz fix ci step [Build with Maven] error

**Comment by tangyang9464** [comment]
@fangzhengjin fixed

**Review by fangzhengjin — APPROVED** [review]
LGTM

**Comment by hsluoyz** [comment]
@tangyang9464 plz always squash/merge your commits into a single commit

**Comment by tangyang9464** [comment]
@hsluoyz got it

**Pull request merged**
